# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0003_auto_20171024_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
        migrations.AlterField(
            model_name='sca',
            name='setor',
            field=models.CharField(choices=[('ALMOXARIFADO', 'ALMOXARIFADO'), ('ASSCOM', 'ASSCOM'), ('ASSJUR', 'ASSJUR'), ('BIOTÉRIO', 'BIOTÉRIO'), ('CCS', 'CCS'), ('CLI', 'CLI'), ('CTEA', 'CTEA'), ('DAAF', 'DAAF'), ('DED', 'DED'), ('DFI', 'DFI'), ('DG', 'DG'), ('DGC', 'DGC'), ('DIC', 'DIC'), ('DIM', 'DIM'), ('DMK', 'DMK'), ('DNG', 'DNG'), ('DTI', 'DTI'), ('GASTRONÔMIA', 'GASTRONÔMIA'), ('GRÁFICA', 'GRÁFICA'), ('ITEC', 'ITEC'), ('ITP', 'ITP'), ('MANUTENÇÃO', 'MANUTENÇÃO'), ('NEAD', 'NEAD'), ('PATRIMÔNIO', 'PATRIMÔNIO'), ('SG', 'SG'), ('SUPAC', 'SUPAC')], max_length=100, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='setor',
            field=models.CharField(max_length=100, verbose_name='Setor'),
        ),
    ]
