# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0004_auto_20171024_2055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoAuto',
            new_name='Tipo',
        ),
    ]
