# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0005_auto_20171024_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sca',
            name='tipo',
            field=models.CharField(choices=[('CARONA', 'CARONA'), ('DELIVERY', 'DELIVERY'), ('ESPECIAL', 'ESPECIAL'), ('FORNECEDOR', 'FORNECEDOR'), ('PRESTADORA DE SERVIÇOS', 'PRESTADORA DE SERVIÇOS'), ('TERCEIRO', 'TERCEIRO')], max_length=100, verbose_name='Tipo'),
        ),
    ]
