# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvrscan', '0002_auto_20171009_1924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dvrs',
            new_name='Dvr',
        ),
    ]
