# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvrscan', '0003_auto_20171009_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dvr',
            options={'ordering': ['name_dvr']},
        ),
        migrations.AlterField(
            model_name='dvr',
            name='status_dvr',
            field=models.BooleanField(verbose_name='Status (Ativo=ONLINE)'),
        ),
    ]
