# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvrscan', '0004_auto_20171010_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dvr',
            options={'ordering': ['name_dvr'], 'verbose_name': 'Cadastro de DVR'},
        ),
    ]
